### 配置端口号
server:
  port: 28103
  shutdown: graceful #优雅停机配置, springboot 2.3.0开始提供

### 选择环境
spring:
  application:
    name: ai-server
  lifecycle:
    timeout-per-shutdown-phase: 30s #优雅停机配置, 设置缓冲器， 最大等待时间  cloud:
  profiles:
    active: dev

moli:
  user-center:
    shiro:
      anon-paths:
        - /actuator/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: never
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      env: ${spring.profiles.active:default}

