<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.moli</groupId>
    <artifactId>moli-project-distribute</artifactId>
    <version>1.0-RELEASE</version>
    <packaging>pom</packaging>

    <name>moli-project-distribute</name>
    <description>Moli microservices aggregator</description>

    <modules>
        <module>moli-distribute-parent</module>
        <module>moli-distribute-common</module>
        <module>moli-gateway</module>
        <module>moli-user-center</module>
        <module>moli-order</module>
        <module>moli-bi</module>
    </modules>

</project>
