
spring:
  cloud:
    gateway:
      enabled:  true
      discovery:
        locator:
          lower-case-service-id: true
      # spring cloud route config -- UserCenter Server
      routes:
      - id: user-center-route
        uri: lb://user-center-server
        predicates:
        - Path=/UserCenter/**
        filters:
        - StripPrefix=1
      # spring cloud route config -- Order Server
      - id: order-route
        uri: lb://order-server
        predicates:
        - Path=/OrderServer/**
        filters:
        - StripPrefix=1
      # spring cloud route config -- BI Server
      - id: bi-route
        uri: lb://bi-server
        predicates:
        - Path=/BiServer/**
        filters:
        - StripPrefix=1


